# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=8)),
                ('cl_no', models.CharField(max_length=4)),
                ('course_name', models.CharField(max_length=100)),
                ('cl_day', models.IntegerField()),
                ('cl_start_time', models.TimeField()),
                ('cl_end_time', models.TimeField()),
                ('cl_room', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(to='table.Program'),
        ),
    ]
