# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CL',
            new_name='Master',
        ),
    ]
