# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20170117_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='lecturer',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
